name: generators
description: A new Flutter package project.
version: 0.0.1
# 7: add publish_to: none
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # 6. add build, source_gen, annotations
  build:
  source_gen: 
  annotations:
    path: ../annotations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # 8. add build_runner
  build_runner: 

flutter:

